version: '3'
services:
  db:
    environment:
      - MYSQL_ROOT_PASSWORD=WeReTheDeadBeatClub
    image: mysql:5.6.39
    ports:
      - 3308:3306
  www:
    build: .
    depends_on:
      - db
    ports:
      - 80:80
    volumes:
      - ./public_html/:/var/www/html/
